--Asian Population
SELECT SUM(CT.POPULATION) FROM CITY CT, COUNTRY CN WHERE CT.COUNTRYCODE = CN.CODE AND CN.CONTINENT ='Asia';

--African Cities
SELECT CT.NAME FROM CITY CT, COUNTRY CN WHERE CT.COUNTRYCODE = CN.CODE AND CN.CONTINENT ='Africa';

--Average Population of Each Continent
SELECT CN.CONTINENT,FLOOR(AVG(CT.POPULATION)) FROM CITY CT, COUNTRY CN WHERE CT.COUNTRYCODE = CN.CODE GROUP BY CN.CONTINENT;

--The Report
SELECT
  CASE
    WHEN G.GRADE < 8 THEN NULL
    ELSE S.NAME
  END,
  G.GRADE,
  S.MARKS
FROM STUDENTS AS S
JOIN GRADES AS G
ON S.MARKS >= G.MIN_MARK AND S.MARKS <= G.MAX_MARK
ORDER BY G.GRADE DESC, S.NAME ASC;