--Placements 
WITH STUDSAL AS ( 
    SELECT S.ID, S.NAME,P.SALARY 
    FROM STUDENTS S,PACKAGES P
    WHERE S.ID = P.ID), 
 FRNDSAL AS (
  SELECT F.ID, F.FRIEND_ID, P.SALARY 
  FROM FRIENDS F, PACKAGES P 
  WHERE P.ID = F.FRIEND_ID) 
SELECT S.NAME FROM STUDSAL S, FRNDSAL F 
WHERE S.ID = F.ID 
AND S.SALARY < F.SALARY 
ORDER BY F.SALARY;

--SQL Project Planning
SELECT S.START_DATE, MIN(E.END_DATE) FROM 
(SELECT START_DATE FROM PROJECTS WHERE START_DATE NOT IN (SELECT END_DATE FROM PROJECTS)) S,
(SELECT END_DATE FROM PROJECTS WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS)) E
WHERE S.START_DATE < E.END_DATE
GROUP BY S.START_DATE
ORDER BY (TO_DATE(MIN(E.END_DATE),'YYYY/MM/DD') -  TO_DATE(S.START_DATE,'YYYY/MM/DD')), START_DATE;
                                                           
                                                           --
