--Placements 
WITH STUDSAL AS ( 
    SELECT S.ID, S.NAME,P.SALARY 
    FROM STUDENTS S,PACKAGES P
    WHERE S.ID = P.ID), 
 FRNDSAL AS (
  SELECT F.ID, F.FRIEND_ID, P.SALARY 
  FROM FRIENDS F, PACKAGES P 
  WHERE P.ID = F.FRIEND_ID) 
SELECT S.NAME FROM STUDSAL S, FRNDSAL F 
WHERE S.ID = F.ID 
AND S.SALARY < F.SALARY 
ORDER BY F.SALARY;
