--Revising Aggregations - The Count Function
SELECT SUM(CNT) FROM (SELECT COUNT(DISTINCT NAME) CNT FROM CITY WHERE POPULATION >100000 GROUP BY NAME);

--Revising Aggregations - The Sum Function
SELECT SUM(POPULATION) FROM CITY WHERE DISTRICT = 'California' GROUP BY DISTRICT;

--Revising Aggregations - Averages
SELECT AVG(POPULATION) FROM CITY WHERE DISTRICT = 'California' GROUP BY DISTRICT;

--Average Population
SELECT ROUND(AVG(POPULATION),0) FROM CITY;

--Japan Population
SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE ='JPN';

--Population Density Difference
SELECT MAX(POPULATION) - MIN(POPULATION) FROM CITY;

--The Blunder
SELECT ROUND((AVG(SALARY) - AVG(REPLACE(SALARY,'0')))+0.5 )  FROM EMPLOYEES;

--Top Earners
SELECT MAX(SALARY*MONTHS), COUNT(*)
FROM EMPLOYEE WHERE (SALARY*MONTHS) = (SELECT MAX(SALARY*MONTHS)
										FROM EMPLOYEE);
										
--Weather Observation Station 2
SELECT ROUND(SUM(LAT_N ),2),ROUND(SUM(LONG_W),2) FROM STATION;

--Weather Observation Station 13
SELECT ROUND(SUM(LAT_N ),4) FROM STATION WHERE LAT_N BETWEEN 38.7880 AND 137.2345;

--Weather Observation Station 14
SELECT ROUND(MAX(LAT_N ),4) FROM STATION WHERE LAT_N < 137.2345;

--Weather Observation Station 15
SELECT ROUND(LONG_W ,4) FROM STATION WHERE LAT_N = (SELECT MAX(LAT_N ) FROM STATION WHERE LAT_N < 137.2345);

--Weather Observation Station 16
SELECT ROUND(MIN(LAT_N ),4) FROM STATION WHERE LAT_N >38.7780;

--Weather Observation Station 17
SELECT ROUND(LONG_W ,4) FROM STATION WHERE LAT_N=(SELECT MIN(LAT_N) FROM STATION WHERE LAT_N >38.7780);

--Weather Observation Station 18
SELECT ROUND((ABS(MIN(LAT_N)- MAX(LAT_N)) + ABS(MIN(LONG_W) -  MAX(LONG_W))),4)  FROM STATION;

--Weather Observation Station 19
SELECT ROUND(SQRT(POWER((MIN(LAT_N)- MAX(LAT_N)),2) + POWER((MIN(LONG_W) -  MAX(LONG_W)),2)),4) FROM STATION;

--Weather Observation Station 20
SELECT ROUND(MEDIAN(LAT_N),4) FROM STATION;
